driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[test::default]
- name: no-fqdn
  run_list:
  - recipe[test::no-fqdn]
  driver:
    network:
      - ['private_network', {ip: '192.168.243.2'}]
- name: add-ons-no-fqdn
  run_list:
  - recipe[test::add-ons-no-fqdn]
  driver:
    network:
      - ['private_network', {ip: '192.168.243.3'}]
