#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_api_token: <%= ENV['DIGITALOCEAN_API_TOKEN'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-12-04-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: ubuntu-14-04-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[chef-server]
  - recipe[test::post-install]
  attributes:
    chef-server:
      api_fqdn: 'chef-server-tk.example.com'

- name: no-fqdn
  run_list:
  - recipe[test]
  - recipe[chef-server]
  attributes:
    chef-server:
      api_fqdn: ''

- name: add-ons-no-fqdn
  run_list:
  - recipe[test]
  - recipe[chef-server]
  - recipe[chef-server::addons]
  attributes:
    chef-server:
      api_fqdn: ''
      addons:
        - opscode-manage
