driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
- name: ubuntu-13.04
- name: centos-6.5
- name: centos-5.10

suites:
- name: default
  run_list:
  - recipe[chef-server]
  attributes: {}
